// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI commands (migrate, generate, etc.) need a non-pooled
    // connection — Neon's pooled endpoint doesn't reliably support the
    // advisory lock `migrate deploy` takes. The app's runtime PrismaClient
    // (src/lib/prisma.ts) still connects via the pooled DATABASE_URL.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
